package frames;

import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import clases.Conectar;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.sql.ResultSet;

/**
 *
 * @author caill
 */
public class Eliminar_tareas extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Eliminar_tareas.class.getName());

    // Variable global para la clase
    int opcionSeleccionada = 0;

    public Eliminar_tareas() {
        initComponents();
        configurarVentana();

        try {
            // Cargamos la imagen desde la ruta de paquetes
            setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/icono_pantalla1.png")));
        } catch (Exception e) {
            System.out.println("No se pudo cargar el icono");
        }

    }

    private void configurarVentana() {
        this.setTitle("Mantenimiento de Datos");
        this.setSize(640, 480);
        this.setResizable(false);
        this.setLocationRelativeTo(null);

        // Desactivamos el botón de ejecución por seguridad al empezar
        btnEliminarDatosSeleccionados.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnSoloAlumnos = new javax.swing.JButton();
        btnSoloCalificaciones = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnReiniciarBaseDatosCompleta = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnGenerarRespado = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        txtConfirmar = new javax.swing.JTextField();
        btnEliminarDatosSeleccionados = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Mantenimiento de Datos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jLabel2.setText("Selecciones los datos que desea eliminar de forma  ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 390, 20));

        jLabel3.setText("permanente. Esta acción no se podrá deshacer.");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel5.setText("Eliminar solo Alumnos");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        btnSoloAlumnos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar-usuario.png"))); // NOI18N
        btnSoloAlumnos.addActionListener(this::btnSoloAlumnosActionPerformed);
        getContentPane().add(btnSoloAlumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 50, 50));

        btnSoloCalificaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar_doc.png"))); // NOI18N
        btnSoloCalificaciones.addActionListener(this::btnSoloCalificacionesActionPerformed);
        getContentPane().add(btnSoloCalificaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 50, 50));

        jLabel4.setText("Eliminar solo Calificaciones Cursos ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        btnReiniciarBaseDatosCompleta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reinicar_db.png"))); // NOI18N
        btnReiniciarBaseDatosCompleta.addActionListener(this::btnReiniciarBaseDatosCompletaActionPerformed);
        getContentPane().add(btnReiniciarBaseDatosCompleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 50, 50));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, -1, -1));

        jLabel7.setText("Reinicar Base de Datos Completa");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));

        btnGenerarRespado.setBackground(new java.awt.Color(255, 204, 102));
        btnGenerarRespado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/respaldo.png"))); // NOI18N
        btnGenerarRespado.setText("Generar Respaldo Ahora");
        btnGenerarRespado.addActionListener(this::btnGenerarRespadoActionPerformed);
        getContentPane().add(btnGenerarRespado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jLabel8.setText("Escriba CONFIRMAR para activar ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, -1));

        txtConfirmar.addActionListener(this::txtConfirmarActionPerformed);
        txtConfirmar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtConfirmarKeyReleased(evt);
            }
        });
        getContentPane().add(txtConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 170, -1));

        btnEliminarDatosSeleccionados.setBackground(new java.awt.Color(255, 51, 51));
        btnEliminarDatosSeleccionados.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminarDatosSeleccionados.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarDatosSeleccionados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar-base-de-datos.png"))); // NOI18N
        btnEliminarDatosSeleccionados.setText("Eliminar Datos Seleccionados");
        btnEliminarDatosSeleccionados.addActionListener(this::btnEliminarDatosSeleccionadosActionPerformed);
        getContentPane().add(btnEliminarDatosSeleccionados, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSoloCalificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSoloCalificacionesActionPerformed
        opcionSeleccionada = 2;
        JOptionPane.showMessageDialog(this, "Seleccionado: Eliminar Calificaciones");
    }//GEN-LAST:event_btnSoloCalificacionesActionPerformed

    private void txtConfirmarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConfirmarKeyReleased
// Usamos equalsIgnoreCase para que no importe si escriben en minúsculas
        if (txtConfirmar.getText().trim().equalsIgnoreCase("CONFIRMAR")) {
            btnEliminarDatosSeleccionados.setEnabled(true);
        } else {
            btnEliminarDatosSeleccionados.setEnabled(false);
        }

    }//GEN-LAST:event_txtConfirmarKeyReleased

    private void btnSoloAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSoloAlumnosActionPerformed

        opcionSeleccionada = 1;
        JOptionPane.showMessageDialog(this, "Seleccionado: Eliminar Alumnos");
    }//GEN-LAST:event_btnSoloAlumnosActionPerformed

    private void btnReiniciarBaseDatosCompletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarBaseDatosCompletaActionPerformed
        opcionSeleccionada = 3;
        JOptionPane.showMessageDialog(this, "¡CUIDADO!: Seleccionado borrar TODO el sistema");
    }//GEN-LAST:event_btnReiniciarBaseDatosCompletaActionPerformed

    private void btnEliminarDatosSeleccionadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarDatosSeleccionadosActionPerformed
        if (opcionSeleccionada == 0) {
            JOptionPane.showMessageDialog(this, "Primero selecciona qué deseas borrar.");
            return;
        }

        int respuesta = JOptionPane.showConfirmDialog(this, "¿Estás seguro? No hay vuelta atrás.", "CONFIRMAR", JOptionPane.YES_NO_OPTION);

        if (respuesta == JOptionPane.YES_OPTION) {
            try {
                // El try-with-resources cierra la conexión automáticamente
                try (Connection cn = Conectar.conexion()) {
                    switch (opcionSeleccionada) {
                        case 1 -> {
                            // Borrar solo alumnos
                            PreparedStatement pst = cn.prepareStatement("DELETE FROM alumnos");
                            pst.executeUpdate();
                        }
                        case 2 -> {
                            // Borrar solo notas (tu tabla real se llama 'notas')
                            PreparedStatement pst = cn.prepareStatement("DELETE FROM notas");
                            pst.executeUpdate();
                        }
                        case 3 -> {
                            // ORDEN CORRECTO para evitar errores de llaves foráneas:
                            // 1. Borramos notas (dependen de alumnos y cursos)
                            cn.prepareStatement("DELETE FROM notas").executeUpdate();
                            // 2. Borramos alumnos
                            cn.prepareStatement("DELETE FROM alumnos").executeUpdate();
                            // 3. Borramos cursos
                            cn.prepareStatement("DELETE FROM curso").executeUpdate();
                        }
                        default -> {
                        }
                    }
                }

                JOptionPane.showMessageDialog(this, "¡Datos borrados con éxito!");
                txtConfirmar.setText(""); // Limpiamos el cuadro
                btnEliminarDatosSeleccionados.setEnabled(false); // Bloqueamos el botón de nuevo
                opcionSeleccionada = 0; // Reseteamos la elección

            } catch (HeadlessException | SQLException e) {
                // Esto capturará si vuelve a haber un error de "no such table"
                JOptionPane.showMessageDialog(this, "Error de base de datos: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnEliminarDatosSeleccionadosActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();

        Principal principal = new Principal();
        principal.setVisible(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGenerarRespadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarRespadoActionPerformed

        java.time.LocalDate fecha = java.time.LocalDate.now();
        String ruta = System.getProperty("user.home") + "/Desktop/Respaldo_Completo_" + fecha + ".txt";

        try (Connection cn = Conectar.conexion(); java.io.FileWriter fw = new java.io.FileWriter(ruta); java.io.PrintWriter pw = new java.io.PrintWriter(fw)) {

            pw.println("--- RESPALDO DE SEGURIDAD INTEGRAL ---");
            pw.println("Fecha: " + fecha);
            pw.println("------------------------------------------\n");

            // 1. RESPALDO DE ALUMNOS
            pw.println(">>> TABLA: ALUMNOS <<<");
            ResultSet rsA = cn.prepareStatement("SELECT * FROM alumnos").executeQuery();
            while (rsA.next()) {
                pw.println("ID: " + rsA.getString(1) + " | Nombre: " + rsA.getString(2) + " " + rsA.getString(3));
            }

            pw.println("\n------------------------------------------\n");

            // 2. RESPALDO DE NOTAS (Lo que te faltaba)
            pw.println(">>> TABLA: NOTAS <<<");
            ResultSet rsN = cn.prepareStatement("SELECT * FROM notas").executeQuery();
            while (rsN.next()) {
                // Ajusta los getString(#) según el orden de tus columnas en la tabla notas
                pw.println("ID Nota: " + rsN.getString(1) + " | Alumno ID: " + rsN.getString(2)
                        + " | Tarea: " + rsN.getString(4) + " | Nota: " + rsN.getString(5));
            }

            JOptionPane.showMessageDialog(this, "Respaldo integral generado en el Escritorio.");
            java.awt.Desktop.getDesktop().open(new java.io.File(ruta));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error en respaldo: " + e.getMessage());
        }

    }//GEN-LAST:event_btnGenerarRespadoActionPerformed

    private void txtConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConfirmarActionPerformed

        if (txtConfirmar.getText().trim().equals("CONFIRMAR")) {
            btnEliminarDatosSeleccionados.setEnabled(true); // Se "desbloquea" el botón rojo
        } else {
            btnEliminarDatosSeleccionados.setEnabled(false); // Sigue bloqueado si borras una letra
        }
    }//GEN-LAST:event_txtConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Eliminar_tareas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminarDatosSeleccionados;
    private javax.swing.JButton btnGenerarRespado;
    private javax.swing.JButton btnReiniciarBaseDatosCompleta;
    private javax.swing.JButton btnSoloAlumnos;
    private javax.swing.JButton btnSoloCalificaciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtConfirmar;
    // End of variables declaration//GEN-END:variables
}
