package frames;

import clases.Conectar;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author caill
 */
public class Gestion_alumnos extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Gestion_alumnos.class.getName());

    public static int idalumno = 0;

    public Gestion_alumnos() {
        initComponents();
        this.setResizable(false);
        this.setTitle("Gestión Alumnos");
        this.setSize(640, 480);
        this.setLocationRelativeTo(null);

        this.cargarTabla();

        try {
            // Cargamos la imagen desde la ruta de paquetes
            setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes//icono_pantalla1.png")));
        } catch (Exception e) {
            System.out.println("No se pudo cargar el icono");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablagestionalumnos = new javax.swing.JTable();
        btnvolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablagestionalumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablagestionalumnos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tablagestionalumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablagestionalumnosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablagestionalumnos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 560, 340));

        btnvolver.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnvolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/volver.png"))); // NOI18N
        btnvolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnvolver.addActionListener(this::btnvolverActionPerformed);
        getContentPane().add(btnvolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 80, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvolverActionPerformed
        this.dispose();

        Registrar_alumnos registrar_alumnos = new Registrar_alumnos();
        registrar_alumnos.setVisible(true);
    }//GEN-LAST:event_btnvolverActionPerformed

    private void tablagestionalumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablagestionalumnosMouseClicked

        // 1. Identificar la fila donde se hizo clic
        int fila_point = tablagestionalumnos.rowAtPoint(evt.getPoint());
        int columna_point = 0; // El ID está en la primera columna

        // 2. Validar que se haya hecho clic sobre una fila válida
        if (fila_point > -1) {
            // 3. Obtener el ID de la tabla y asignarlo a la variable estática idalumno
            // Importante: Casteamos a (int) porque el valor viene como Object
            idalumno = (int) tablagestionalumnos.getValueAt(fila_point, columna_point);

            // 4. Abrir la interfaz de Información y cerrar la actual
            Informacion_alumnos informacion = new Informacion_alumnos();
            informacion.setVisible(true);
            this.dispose();
        }

    }//GEN-LAST:event_tablagestionalumnosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Gestion_alumnos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnvolver;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablagestionalumnos;
    // End of variables declaration//GEN-END:variables

    private void cargarTabla() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellidos");
        modelo.addColumn("Grado");
        modelo.addColumn("Telefono");
        modelo.addColumn("Materia");

        tablagestionalumnos.setModel(modelo);

        // 1. Definimos la base de la consulta
        String sql = "SELECT a.id_alumno, a.nombre, a.apellidos, a.grado, a.telefono, c.nombre_curso "
                + "FROM alumnos a "
                + "INNER JOIN curso c ON a.id_curso_asignado = c.id_curso";

        // 2. Si NO es Administrador, filtramos por su ID de docente
        if (!Login.rolUsuarioLogeado.equals("Administrador")) {
            sql += " WHERE a.id_docente = ?";
        }

        try {
            Connection con = Conectar.conexion();
            PreparedStatement ps = con.prepareStatement(sql);

            // 3. Solo pasamos el parámetro si el SQL lleva el WHERE
            if (!Login.rolUsuarioLogeado.equals("Administrador")) {
                ps.setInt(1, Login.idUsuarioLogeado);
            }

            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                Object[] fila = new Object[6];
                fila[0] = rs.getInt(1);
                fila[1] = rs.getString(2);
                fila[2] = rs.getString(3);
                fila[3] = rs.getString(4);
                fila[4] = rs.getString(5);
                fila[5] = rs.getString(6);
                modelo.addRow(fila);
            }

            rs.close();
            ps.close();
            con.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar alumnos: " + e.getMessage());
        }
    }

}
