package frames;

import clases.Conectar;
import java.awt.Toolkit;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.font.Standard14Fonts;

/**
 *
 * @author caill
 */
public class Gestion_calificaciones extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Gestion_calificaciones.class.getName());

    DefaultTableModel modeloGeneral = new DefaultTableModel();

    public Gestion_calificaciones() {
        initComponents();
        cargarTablaGeneral();
        configurarVentana();

        try {
            // Cargamos la imagen desde la ruta de paquetes
            setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/icono_pantalla1.png")));
        } catch (Exception e) {
            System.out.println("No se pudo cargar el icono");
        }

    }

    private void configurarVentana() {
        this.setTitle("Gestión General de Calificaciones");
        this.setSize(640, 480);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnvolver = new javax.swing.JButton();
        btnimprimir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_informacion_calificaciones = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnvolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/volver.png"))); // NOI18N
        btnvolver.addActionListener(this::btnvolverActionPerformed);
        getContentPane().add(btnvolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 80, -1));

        btnimprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imprimir.png"))); // NOI18N
        btnimprimir.addActionListener(this::btnimprimirActionPerformed);
        getContentPane().add(btnimprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 80, 40));

        tabla_informacion_calificaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla_informacion_calificaciones);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 570, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnimprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimprimirActionPerformed
        try (PDDocument doc = new PDDocument()) {
            PDPage page = new PDPage();
            doc.addPage(page);

            // --- OBTENER FECHA ACTUAL ---
            java.time.LocalDate fechaActual = java.time.LocalDate.now();
            String fechaTexto = "Fecha de emisión: " + fechaActual.getDayOfMonth() + "/"
                    + fechaActual.getMonthValue() + "/" + fechaActual.getYear();

            try (PDPageContentStream content = new PDPageContentStream(doc, page)) {
                // Título Principal
                content.beginText();
                content.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD), 18);
                content.newLineAtOffset(150, 750);
                content.showText("LISTADO GENERAL DE CALIFICACIONES");
                content.endText();

                // --- AGREGAR FECHA (Día/Mes/Año) ---
                content.beginText();
                content.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA), 10);
                content.newLineAtOffset(420, 730); // Posición en la esquina superior derecha
                content.showText(fechaTexto);
                content.endText();

                int y = 700;
                int rowHeight = 20;

                // --- ENCABEZADOS (Ajustados exactamente a tus 5 columnas) ---
                content.setNonStrokingColor(225 / 255f, 225 / 255f, 225 / 255f);
                content.addRect(50, y, 500, rowHeight);
                content.fill();

                content.setNonStrokingColor(0, 0, 0);
                content.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD), 10);

                content.beginText();
                content.newLineAtOffset(55, y + 6);
                content.showText("ID");            // Columna 0
                content.newLineAtOffset(30, 0);
                content.showText("ALUMNO");        // Columna 1
                content.newLineAtOffset(150, 0);
                content.showText("MATERIA");       // Columna 2
                content.newLineAtOffset(120, 0);
                content.showText("PROM.");         // Columna 3
                content.newLineAtOffset(70, 0);
                content.showText("ESTATUS");       // Columna 4
                content.endText();

                // --- DATOS DE LA TABLA ---
                content.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA), 9);
                y -= rowHeight;

                for (int i = 0; i < tabla_informacion_calificaciones.getRowCount(); i++) {
                    content.setLineWidth(0.5f);
                    content.addRect(50, y, 500, rowHeight);
                    content.stroke();

                    // Extraemos los datos basándonos en tu tabla real (Índices 0 al 4)
                    String id = tabla_informacion_calificaciones.getValueAt(i, 0).toString();
                    String nom = tabla_informacion_calificaciones.getValueAt(i, 1).toString();
                    String mat = tabla_informacion_calificaciones.getValueAt(i, 2).toString();
                    String pro = tabla_informacion_calificaciones.getValueAt(i, 3).toString();
                    String est = tabla_informacion_calificaciones.getValueAt(i, 4).toString();

                    // Imprimimos los datos
                    content.beginText();
                    content.newLineAtOffset(55, y + 6);
                    content.showText(id);
                    content.newLineAtOffset(30, 0);
                    content.showText(nom);
                    content.newLineAtOffset(150, 0);
                    content.showText(mat);
                    content.newLineAtOffset(120, 0);
                    content.showText(pro);
                    content.newLineAtOffset(70, 0);
                    content.showText(est);
                    content.endText();

                    y -= rowHeight;
                    if (y < 60) {
                        break;
                    }
                }
            }

            // Guardar y abrir
            String ruta = System.getProperty("user.home") + File.separator + "Documents" + File.separator + "Reporte_Calificaciones.pdf";
            doc.save(ruta);
            java.awt.Desktop.getDesktop().open(new File(ruta));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnimprimirActionPerformed

    private void btnvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvolverActionPerformed

        this.dispose();

        Principal principal = new Principal();
        principal.setVisible(true);

    }//GEN-LAST:event_btnvolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Gestion_calificaciones().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnimprimir;
    private javax.swing.JButton btnvolver;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla_informacion_calificaciones;
    // End of variables declaration//GEN-END:variables

    private void cargarTablaGeneral() {
        modeloGeneral = new DefaultTableModel();
        modeloGeneral.addColumn("ID");
        modeloGeneral.addColumn("Alumno");
        modeloGeneral.addColumn("Materia");
        modeloGeneral.addColumn("Promedio");
        modeloGeneral.addColumn("Estatus");
        tabla_informacion_calificaciones.setModel(modeloGeneral);

        // 1. Preparamos el SQL base
        String sql = "SELECT a.id_alumno, a.nombre || ' ' || a.apellidos AS nombre, "
                + "n.materia, AVG(n.calificacion) AS prom "
                + "FROM alumnos a LEFT JOIN notas n ON a.id_alumno = n.id_alumno_nota ";

        // 2. Filtramos si el usuario NO es Administrador
        if (!Login.rolUsuarioLogeado.equals("Administrador")) {
            sql += " WHERE a.id_docente = ? ";
        }

        // 3. Agregamos el agrupamiento al final
        sql += " GROUP BY a.id_alumno, n.materia";

        try {
            Connection con = Conectar.conexion();
            PreparedStatement ps = con.prepareStatement(sql);

            // 4. Pasamos el ID del docente si corresponde
            if (!Login.rolUsuarioLogeado.equals("Administrador")) {
                ps.setInt(1, Login.idUsuarioLogeado);
            }

            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                Object[] fila = new Object[5];
                double prom = rs.getDouble("prom");

                fila[0] = rs.getInt("id_alumno");
                fila[1] = rs.getString("nombre");
                fila[2] = rs.getString("materia") != null ? rs.getString("materia") : "Sin Materia";
                fila[3] = (prom > 0) ? String.format("%.2f", prom) : "0.00";

                if (prom >= 40) {
                    fila[4] = "Aprobado";
                } else {
                    fila[4] = (prom == 0) ? "-" : "Reprobado";
                }
                modeloGeneral.addRow(fila);
            }

            rs.close();
            ps.close();
            con.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }

}
