package frames;

import clases.Conectar;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author caill
 */
public class Gestion_cursos extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Gestion_cursos.class.getName());

    public Gestion_cursos() {
        initComponents();
        this.setResizable(false);
        this.setTitle("Gestión de Cursos");
        this.setSize(640, 480);
        this.setLocationRelativeTo(null);

        this.cargarTabla();

        try {
            // Cargamos la imagen desde la ruta de paquetes
            setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/icono_pantalla1.png")));
        } catch (Exception e) {
            System.out.println("No se pudo cargar el icono");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablagestioncurso = new javax.swing.JTable();
        btnvolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablagestioncurso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablagestioncurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablagestioncursoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablagestioncurso);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 570, 300));

        btnvolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/volver.png"))); // NOI18N
        btnvolver.addActionListener(this::btnvolverActionPerformed);
        getContentPane().add(btnvolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, 70, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvolverActionPerformed

        this.dispose();

        Principal principal = new Principal();
        principal.setVisible(true);
    }//GEN-LAST:event_btnvolverActionPerformed

    private void tablagestioncursoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablagestioncursoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tablagestioncursoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Gestion_cursos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnvolver;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablagestioncurso;
    // End of variables declaration//GEN-END:variables

    private void cargarTabla() {

        DefaultTableModel modelo = new DefaultTableModel();
        // Definimos solo las columnas de la tabla cursos
        modelo.addColumn("ID");
        modelo.addColumn("Nombre del Curso");

        tablagestioncurso.setModel(modelo);

        // Consulta simple a la tabla curso
        String sql = "SELECT id_curso, nombre_curso FROM curso";

        try {
            Connection con = Conectar.conexion();
            PreparedStatement ps = con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {

                Object[] fila = new Object[2];

                fila[0] = rs.getInt(1);    // id_curso
                fila[1] = rs.getString(2); // nombre_curso

                modelo.addRow(fila);
            }

            rs.close();
            ps.close();
            con.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar cursos: " + e.getMessage());
        }
    }

}
