package frames;

import clases.Conectar;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author caill
 */
public class Informacion_calificaciones extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Informacion_calificaciones.class.getName());

    private int idAlumnoLocal;
    private String tareaOriginal;

    public Informacion_calificaciones(int id_alumno, String tarea, int nota) {
        initComponents();
        configurarVentana();
        this.idAlumnoLocal = id_alumno;
        this.tareaOriginal = tarea;

        // Seteamos los textos con lo que recibimos
        txtalumno.setText("ID Alumno: " + id_alumno); // O el nombre si lo pasas
        txttarea.setText(tarea);
        txtcalificacion.setText(String.valueOf(nota));

        txtalumno.setEditable(false); // El ID/Nombre no se toca
        cargarTablaCalificaciones();

        try {
            // Cargamos la imagen desde la ruta de paquetes
            setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/icono_pantalla1.png")));
        } catch (Exception e) {
            System.out.println("No se pudo cargar el icono");
        }

    }

    private void configurarVentana() {
        this.setTitle("Información de calificaciones");
        this.setSize(640, 480);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtcalificacion = new javax.swing.JTextField();
        txtalumno = new javax.swing.JTextField();
        txttarea = new javax.swing.JTextField();
        btnactualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_informarcion_calificaciones = new javax.swing.JTable();
        btnvolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Alumno:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel2.setText("Tarea/actividad:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel3.setText("Calificación:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));
        getContentPane().add(txtcalificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 150, -1));
        getContentPane().add(txtalumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 150, -1));
        getContentPane().add(txttarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 150, -1));

        btnactualizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnactualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar.png"))); // NOI18N
        btnactualizar.setText("Actualizar");
        btnactualizar.addActionListener(this::btnactualizarActionPerformed);
        getContentPane().add(btnactualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        tabla_informarcion_calificaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla_informarcion_calificaciones);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 420, 280));

        btnvolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/volver.png"))); // NOI18N
        btnvolver.addActionListener(this::btnvolverActionPerformed);
        getContentPane().add(btnvolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 80, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed

        String nuevaTarea = txttarea.getText().trim();
        String nuevaNotaStr = txtcalificacion.getText().trim();

        if (nuevaTarea.isEmpty() || nuevaNotaStr.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debes llenar todos los campos");
        } else {
            try {
                int nuevaNota = Integer.parseInt(nuevaNotaStr);

                // SQL para actualizar usando la tarea original como referencia
                String sql = "UPDATE notas SET tarea = ?, calificacion = ? WHERE id_alumno_nota = ? AND tarea = ?";

                try (Connection con = Conectar.conexion(); PreparedStatement ps = con.prepareStatement(sql)) {

                    ps.setString(1, nuevaTarea);
                    ps.setInt(2, nuevaNota);
                    ps.setInt(3, idAlumnoLocal);
                    ps.setString(4, tareaOriginal);

                    int resultado = ps.executeUpdate();

                    if (resultado > 0) {
                        JOptionPane.showMessageDialog(null, "¡Calificación actualizada con éxito!");
                        this.dispose(); // Cerramos esta ventana y volvemos a la anterior
                    }
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "La calificación debe ser un número entero (10-70)");
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Error al actualizar: " + e.getMessage());
            }
        }

    }//GEN-LAST:event_btnactualizarActionPerformed

    private void btnvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvolverActionPerformed

        this.dispose();

        Informacion_alumnos informacion_alumnos = new Informacion_alumnos();
        informacion_alumnos.setVisible(true);

    }//GEN-LAST:event_btnvolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Informacion_calificaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            // Pasamos valores por defecto (0, "", 0) para que compile sin errores
            new Informacion_calificaciones(0, "", 0).setVisible(true);
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btnvolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla_informarcion_calificaciones;
    private javax.swing.JTextField txtalumno;
    private javax.swing.JTextField txtcalificacion;
    private javax.swing.JTextField txttarea;
    // End of variables declaration//GEN-END:variables

    private void cargarTablaCalificaciones() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Tarea / Actividad");
        model.addColumn("Calificación");
        tabla_informarcion_calificaciones.setModel(model);

        String sql = "SELECT tarea, calificacion FROM notas WHERE id_alumno_nota = ?";

        try (Connection con = Conectar.conexion(); PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setInt(1, idAlumnoLocal);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                Object[] fila = new Object[2];
                fila[0] = rs.getString("tarea");
                fila[1] = rs.getInt("calificacion");
                model.addRow(fila);
            }
        } catch (SQLException e) {
            System.err.println("Error al llenar tabla: " + e.getMessage());
        }
    }

}
