package frames;

//import clases.Conectar;
import clases.Conectar;
import java.awt.Toolkit;
import java.io.File;
import javax.swing.table.DefaultTableModel;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.font.Standard14Fonts;

/**
 *
 * @author caill
 */
public class Informacion_alumnos extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Informacion_alumnos.class.getName());

    private int idAlumno;
    private String idCursoAlumno;

    DefaultTableModel model = new DefaultTableModel();

    public static int idcalificacion = 0;

    public Informacion_alumnos() {
        initComponents();
        this.idAlumno = Gestion_alumnos.idalumno; // Recuperamos el ID seleccionado

        configurarVentana();
        bloquearCampos();
        cargarDatosAlumno();
        cargarTablaYStatus();

        try {
            // Cargamos la imagen desde la ruta de paquetes
            setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/icono_pantalla1.png")));
        } catch (Exception e) {
            System.out.println("No se pudo cargar el icono");
        }

        tablainformacionalumno.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mousePressed(java.awt.event.MouseEvent e) {
                if (javax.swing.SwingUtilities.isRightMouseButton(e)) {
                    int fila = tablainformacionalumno.rowAtPoint(e.getPoint());
                    int columna = tablainformacionalumno.columnAtPoint(e.getPoint());

                    if (fila >= 0) {
                        tablainformacionalumno.setRowSelectionInterval(fila, fila);

                        // --- PROTECCIÓN CONTRA NULL ---
                        // Ahora Materia es 0, Tarea es 1 y Nota es 2
                        Object valorMateria = tablainformacionalumno.getValueAt(fila, 0);
                        Object valorTarea = tablainformacionalumno.getValueAt(fila, 1);
                        Object valorNota = tablainformacionalumno.getValueAt(fila, 2);

                        if (valorTarea != null && valorNota != null) {
                            String materiaActual = (valorMateria != null) ? valorMateria.toString() : "";
                            String tareaActual = valorTarea.toString();
                            String notaActual = valorNota.toString();

                            int notaEntera = Integer.parseInt(notaActual);

                            // Abrimos la ventana de edición pasando los nuevos datos
                            Informacion_calificaciones edicion = new Informacion_calificaciones(idAlumno, tareaActual, notaEntera);
                            edicion.setVisible(true);
                            
                               Informacion_alumnos.this.dispose();
                         
                        }
                        
                    }
                }
            }
        });
    }

    private void configurarVentana() {
        this.setTitle("Información del Alumno - ID: " + idAlumno);
        this.setSize(640, 480);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    private void bloquearCampos() {
        txtnombre.setEditable(false);
        txtapellido.setEditable(false);
        txttelefono.setEditable(false);
        txtcalificacion.setEditable(false);
        txtestatus.setEditable(false);
        cmbgrado.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txttelefono = new javax.swing.JTextField();
        cmbgrado = new javax.swing.JComboBox<>();
        txtnombre = new javax.swing.JTextField();
        txtapellido = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablainformacionalumno = new javax.swing.JTable();
        btnvolver = new javax.swing.JButton();
        btnregistrarcalificacion = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtcalificacion = new javax.swing.JTextField();
        btnImprimir = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtestatus = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jLabel2.setText("Apellidos:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, -1));

        jLabel3.setText("Grado:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, -1));

        jLabel4.setText("Telefono:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, -1, -1));
        getContentPane().add(txttelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 120, -1));

        cmbgrado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione grado:", "1A", "1B", "2A", "2B", "3A", "3B", "4A", "4B", "5A", "5B", "6A", "6B", "7A", "7B", "8A", "8B" }));
        cmbgrado.setToolTipText("");
        getContentPane().add(cmbgrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 140, -1));
        getContentPane().add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 120, -1));
        getContentPane().add(txtapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 120, -1));

        tablainformacionalumno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablainformacionalumno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane1.setViewportView(tablainformacionalumno);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 540, 220));

        btnvolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/volver.png"))); // NOI18N
        btnvolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnvolver.addActionListener(this::btnvolverActionPerformed);
        getContentPane().add(btnvolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 80, 40));

        btnregistrarcalificacion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnregistrarcalificacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/estrellas.png"))); // NOI18N
        btnregistrarcalificacion.setText("Registrar calificación");
        btnregistrarcalificacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnregistrarcalificacion.addActionListener(this::btnregistrarcalificacionActionPerformed);
        getContentPane().add(btnregistrarcalificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 190, 40));

        jLabel5.setText("Calificación:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 70, -1));
        getContentPane().add(txtcalificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 140, -1));

        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imprimir.png"))); // NOI18N
        btnImprimir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnImprimir.addActionListener(this::btnImprimirActionPerformed);
        getContentPane().add(btnImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, 80, 50));

        jLabel6.setText("Estatus:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 80, -1, -1));
        getContentPane().add(txtestatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 120, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvolverActionPerformed
        this.dispose();

        Gestion_alumnos gestion_alumnos = new Gestion_alumnos();
        gestion_alumnos.setVisible(true);
    }//GEN-LAST:event_btnvolverActionPerformed

    private void btnregistrarcalificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarcalificacionActionPerformed

// 1. Creamos la lista de materias (deben ser IGUALES a las de tu base de datos)
        String[] opcionesMaterias = {"Matemáticas", "Lenguaje", "Historia", "Ciencias Naturales", "Inglés", "Tecnología", "Música"};

        // 2. Usamos un ComboBox dentro del JOptionPane
        String materia = (String) JOptionPane.showInputDialog(
                this,
                "Seleccione la materia:",
                "Registro de Calificaciones",
                JOptionPane.QUESTION_MESSAGE,
                null,
                opcionesMaterias,
                opcionesMaterias[0]
        );

        // Si el usuario cancela la selección, salimos
        if (materia == null) {
            return;
        }

        // 3. Pedimos el resto de los datos normalmente
        String tarea = JOptionPane.showInputDialog(this, "Ingrese el nombre de la tarea:");
        String notaStr = JOptionPane.showInputDialog(this, "Ingrese la calificación (10-70):");

        if (tarea != null && !tarea.isEmpty() && notaStr != null && !notaStr.isEmpty()) {
            try {
                int calificacion = Integer.parseInt(notaStr);

                // 4. Tu SQL se mantiene igual, pero ahora la 'materia' viene limpia y sin errores
                String sql = "INSERT INTO notas (id_alumno_nota, id_curso_nota, tarea, calificacion, materia) VALUES (?, ?, ?, ?, ?)";

                try (Connection con = Conectar.conexion(); PreparedStatement ps = con.prepareStatement(sql)) {
                    ps.setInt(1, idAlumno);
                    ps.setString(2, idCursoAlumno);
                    ps.setString(3, tarea);
                    ps.setInt(4, calificacion);
                    ps.setString(5, materia); // <-- Ahora siempre será "Historia" y nunca "Hsitoria"

                    int resultado = ps.executeUpdate();
                    if (resultado > 0) {
                        JOptionPane.showMessageDialog(this, "¡Nota de " + materia + " registrada!");
                        cargarTablaYStatus();
                    }
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "La nota debe ser un número.");
            }
        }

    }//GEN-LAST:event_btnregistrarcalificacionActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed

// 1. Crear el documento PDF
        try (PDDocument documento = new PDDocument()) {
            PDPage pagina = new PDPage();
            documento.addPage(pagina);

            // --- OBTENER FECHA ACTUAL (Añadido) ---
            java.time.LocalDate fechaActual = java.time.LocalDate.now();
            String fechaTexto = "Fecha: " + fechaActual.getDayOfMonth() + "/"
                    + fechaActual.getMonthValue() + "/" + fechaActual.getYear();

            try (PDPageContentStream contenido = new PDPageContentStream(documento, pagina)) {
                // --- TÍTULO ---
                contenido.beginText();
                contenido.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD), 18);
                contenido.newLineAtOffset(50, 750);
                contenido.showText("REPORTE DE CALIFICACIONES");
                contenido.endText();

                // --- FECHA EN EL REPORTE ---
                contenido.beginText();
                contenido.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA), 10);
                contenido.newLineAtOffset(450, 750);
                contenido.showText(fechaTexto);
                contenido.endText();

                // --- DATOS DEL ALUMNO ---
                contenido.beginText();
                contenido.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD), 12);
                contenido.newLineAtOffset(50, 720);
                contenido.showText("Alumno: " + txtnombre.getText() + " " + txtapellido.getText());
                contenido.endText();

                int y = 680;
                int rowHeight = 20;

                // --- ENCABEZADOS ---
                contenido.setNonStrokingColor(225 / 255f, 225 / 255f, 225 / 255f);
                contenido.addRect(50, y, 500, rowHeight);
                contenido.fill();

                contenido.setNonStrokingColor(0, 0, 0);
                contenido.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD), 11);
                contenido.beginText();
                contenido.newLineAtOffset(55, y + 6);
                contenido.showText("Materia");
                contenido.newLineAtOffset(150, 0);
                contenido.showText("Tarea / Actividad");
                contenido.newLineAtOffset(200, 0);
                contenido.showText("Nota");
                contenido.endText();

                y -= rowHeight;
                contenido.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA), 10);

                // --- 2. RECORRER LA TABLA CON PROTECCIÓN ANTI-NULL ---
                for (int i = 0; i < tablainformacionalumno.getRowCount(); i++) {
                    contenido.setLineWidth(0.5f);
                    contenido.addRect(50, y, 500, rowHeight);
                    contenido.stroke();

                    // Validación: Si el objeto es null, usamos un texto vacío "" para evitar el error
                    Object valMat = tablainformacionalumno.getValueAt(i, 0);
                    Object valTar = tablainformacionalumno.getValueAt(i, 1);
                    Object valNot = tablainformacionalumno.getValueAt(i, 2);

                    String mat = (valMat != null) ? valMat.toString() : "---";
                    String tar = (valTar != null) ? valTar.toString() : "---";
                    String not = (valNot != null) ? valNot.toString() : "0.0";

                    contenido.beginText();
                    contenido.newLineAtOffset(55, y + 6);
                    contenido.showText(mat);
                    contenido.newLineAtOffset(150, 0);
                    contenido.showText(tar);
                    contenido.newLineAtOffset(200, 0);
                    contenido.showText(not);
                    contenido.endText();

                    y -= rowHeight;
                    if (y < 120) {
                        break;
                    }
                }

                // --- 3. PROMEDIO Y ESTATUS ---
                y -= 30;
                contenido.beginText();
                contenido.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD), 12);
                contenido.newLineAtOffset(50, y);
                contenido.showText("Promedio Final: " + txtcalificacion.getText());
                y -= 20;
                contenido.newLineAtOffset(0, -20);
                contenido.showText("Estado: " + txtestatus.getText());
                contenido.endText();
            }

            // 4. Guardar
            String ruta = System.getProperty("user.home") + "/Desktop/Reporte_" + txtnombre.getText() + ".pdf";
            documento.save(ruta);
            JOptionPane.showMessageDialog(this, "PDF generado con éxito en el Escritorio.");
            java.awt.Desktop.getDesktop().open(new java.io.File(ruta));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al generar PDF: " + e.getMessage());
        }
    }//GEN-LAST:event_btnImprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Informacion_alumnos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnregistrarcalificacion;
    private javax.swing.JButton btnvolver;
    private javax.swing.JComboBox<String> cmbgrado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablainformacionalumno;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtcalificacion;
    private javax.swing.JTextField txtestatus;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables

    private void cargarDatosAlumno() {
        String sql = "SELECT nombre, apellidos, grado, telefono, id_curso_asignado FROM alumnos WHERE id_alumno = ?";

        try {
            Connection con = Conectar.conexion();
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setInt(1, idAlumno);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                txtnombre.setText(rs.getString("nombre"));
                txtapellido.setText(rs.getString("apellidos"));
                txttelefono.setText(rs.getString("telefono"));

                // Para el JComboBox:
                String gradoDB = rs.getString("grado").trim();
                System.out.println("Grado en DB: [" + gradoDB + "]");
                cmbgrado.setSelectedItem(gradoDB);

                // Guardamos el curso para usarlo en el registro de notas
                idCursoAlumno = rs.getString("id_curso_asignado");
            }

            // Cerramos los recursos
            rs.close();
            ps.close();
            con.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al cargar datos: " + e.getMessage());
        }
    }

    private void editarNota(String tareaOriginal, String notaOriginal) {
        // 1. Pedir los nuevos datos
        String nuevaTarea = JOptionPane.showInputDialog(this, "Modificar nombre de la tarea:", tareaOriginal);
        String nuevaNotaStr = JOptionPane.showInputDialog(this, "Modificar calificación (10-70):", notaOriginal);

        if (nuevaTarea != null && !nuevaTarea.isEmpty() && nuevaNotaStr != null && !nuevaNotaStr.isEmpty()) {
            try {
                int nuevaNota = Integer.parseInt(nuevaNotaStr);

                // 2. SQL para actualizar basándonos en el ID del alumno y el nombre de la tarea
                String sql = "UPDATE notas SET tarea = ?, calificacion = ? WHERE id_alumno_nota = ? AND tarea = ?";

                try (Connection con = Conectar.conexion(); PreparedStatement ps = con.prepareStatement(sql)) {

                    ps.setString(1, nuevaTarea);
                    ps.setInt(2, nuevaNota);
                    ps.setInt(3, idAlumno);
                    ps.setString(4, tareaOriginal);

                    int exito = ps.executeUpdate();

                    if (exito > 0) {
                        JOptionPane.showMessageDialog(this, "¡Nota actualizada!");
                        // 3. Esto refresca la tabla, el promedio y el color del estatus (Escala Chilena)
                        cargarTablaYStatus();
                    }

                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(this, "Error al actualizar: " + e.getMessage());
                }

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Ingresa un número válido (10-70).");
            }
        }
    }

    private void cargarTablaYStatus() {
        DefaultTableModel modelo = new DefaultTableModel();
        // Agregamos la nueva columna al inicio o donde prefieras
        modelo.addColumn("Materia");
        modelo.addColumn("Tarea / Actividad");
        modelo.addColumn("Calificación");
        tablainformacionalumno.setModel(modelo);

        double sumaNotas = 0;
        int contadorTareas = 0;

        // Actualizamos el SQL para traer la columna materia
        String sql = "SELECT materia, tarea, calificacion FROM notas WHERE id_alumno_nota = ?";

        try (Connection con = Conectar.conexion(); PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setInt(1, idAlumno);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                // Ahora el objeto tiene 3 espacios
                Object[] fila = new Object[3];
                int nota = rs.getInt("calificacion");

                // Llenamos la fila con los datos de la DB
                fila[0] = rs.getString("materia"); // Nueva columna
                fila[1] = rs.getString("tarea");
                fila[2] = nota;

                sumaNotas += nota;
                contadorTareas++;
                modelo.addRow(fila);
            }

            // --- Lógica de promedio y estatus (se mantiene igual) ---
            if (contadorTareas > 0) {
                double promedio = sumaNotas / contadorTareas;
                txtcalificacion.setText(String.format("%.2f", promedio));

                if (promedio >= 40) {
                    txtestatus.setText("Aprobado");
                    txtestatus.setForeground(new java.awt.Color(0, 102, 255));
                } else {
                    txtestatus.setText("Reprobado");
                    txtestatus.setForeground(java.awt.Color.RED);
                }
            } else {
                txtcalificacion.setText("0.00");
                txtestatus.setText("Sin Notas");
                txtestatus.setForeground(java.awt.Color.BLACK);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al cargar calificacion: " + e.getMessage());
        }
    }

}
