package frames;

import clases.Conectar;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.UnsupportedEncodingException;
import java.security.NoSuchAlgorithmException;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author caill
 */
public class Login extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    public static int idUsuarioLogeado;
    public static String rolUsuarioLogeado;
    public static String nombreUsuario;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();

        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("Iniciar Sesión");
        this.setSize(new Dimension(400, 400));

        try {
            // Cargamos la imagen desde la ruta de paquetes
            setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/icono_pantalla1.png")));
        } catch (Exception e) {
            System.out.println("No se pudo cargar el icono");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        txtpassword = new javax.swing.JPasswordField();
        btnIngresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblregistrate = new javax.swing.JLabel();
        lblOjo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/user.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 116, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/candado.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 165, -1, 30));

        txtusuario.addActionListener(this::txtusuarioActionPerformed);
        getContentPane().add(txtusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 190, -1));

        txtpassword.addActionListener(this::txtpasswordActionPerformed);
        getContentPane().add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 190, -1));

        btnIngresar.setBackground(new java.awt.Color(0, 102, 204));
        btnIngresar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnIngresar.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresar.setText("Ingresar");
        btnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresar.addActionListener(this::btnIngresarActionPerformed);
        getContentPane().add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 190, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel1.setText("¡Bienvenido!");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        jLabel4.setText("Por favor, inicia sesión en tu cuenta");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        lblregistrate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblregistrate.setForeground(new java.awt.Color(0, 51, 255));
        lblregistrate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/registro.png"))); // NOI18N
        lblregistrate.setText("¿No tienes cuenta? Regístrate aquí");
        lblregistrate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblregistrate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblregistrateMouseClicked(evt);
            }
        });
        getContentPane().add(lblregistrate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, -1, -1));

        lblOjo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ojo_cerrado.png"))); // NOI18N
        lblOjo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblOjo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblOjoMousePressed(evt);
            }
        });
        getContentPane().add(lblOjo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 20, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed

        String usuario = txtusuario.getText();
        String password = new String(txtpassword.getPassword());

        // 1. Ciframos la contraseña para compararla con la BD
        String passwordCifrada = cifrarPassword(password);

        try (java.sql.Connection cn = Conectar.conexion()) {
            // 2. Traemos el ID y el ROL (tipo_nivel) de la base de datos
            String sql = "SELECT id_usuario, tipo_nivel FROM usuarios WHERE username=? AND password=?";
            PreparedStatement ps = cn.prepareStatement(sql);
            ps.setString(1, usuario);
            ps.setString(2, passwordCifrada);

            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                // 3. GUARDAMOS LOS DATOS EN LAS VARIABLES ESTÁTICAS
                idUsuarioLogeado = rs.getInt("id_usuario");
                rolUsuarioLogeado = rs.getString("tipo_nivel");

                JOptionPane.showMessageDialog(this, "Bienvenido " + usuario);

                // 4. ABRIMOS LA PRINCIPAL
                new Principal().setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void txtusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusuarioActionPerformed

        txtpassword.requestFocus();

    }//GEN-LAST:event_txtusuarioActionPerformed

    private void txtpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpasswordActionPerformed

        btnIngresar.doClick();

    }//GEN-LAST:event_txtpasswordActionPerformed

    private void lblregistrateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblregistrateMouseClicked

        // Creamos la instancia de tu ventana de registro
        Registro_usuario registro = new Registro_usuario(); // O el nombre que tenga tu clase de registro
        registro.setVisible(true);

        // Cerramos o escondemos el Login
        this.dispose();

    }//GEN-LAST:event_lblregistrateMouseClicked

    private void lblOjoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOjoMousePressed

        try {
            if (txtpassword.getEchoChar() != (char) 0) {
                // MOSTRAR
                txtpassword.setEchoChar((char) 0);

                // Verificamos si la imagen existe antes de cargarla
                java.net.URL imgUrl = getClass().getResource("/imagenes/ojo_abierto.png");
                if (imgUrl != null) {
                    lblOjo.setIcon(new javax.swing.ImageIcon(imgUrl));
                } else {
                    System.out.println("Error: No se encontró la imagen ojo_abierto.png");
                }

            } else {
                // OCULTAR
                txtpassword.setEchoChar('•');

                java.net.URL imgUrl = getClass().getResource("/imagenes/ojo_cerrado.png");
                if (imgUrl != null) {
                    lblOjo.setIcon(new javax.swing.ImageIcon(imgUrl));
                } else {
                    System.out.println("Error: No se encontró la imagen ojo_cerrado.png");
                }
            }
        } catch (Exception e) {
            System.err.println("Error al cambiar el icono: " + e.getMessage());
        }

    }//GEN-LAST:event_lblOjoMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblOjo;
    private javax.swing.JLabel lblregistrate;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables

    public String cifrarPassword(String password) {
        try {
            java.security.MessageDigest md = java.security.MessageDigest.getInstance("SHA-256");
            byte[] hash = md.digest(password.getBytes("UTF-8"));
            StringBuilder sb = new StringBuilder();
            for (byte b : hash) {
                sb.append(String.format("%02x", b));
            }
            return sb.toString();
        } catch (UnsupportedEncodingException | NoSuchAlgorithmException e) {
            throw new RuntimeException(e);
        }
    }

}
