package frames;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author caill
 */
public class Principal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Principal.class.getName());

    /**
     * Creates new form Principal2
     */
    public Principal() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("Principal");
        this.setSize(new Dimension(640, 480));

        // Aquí aplicamos el filtro de seguridad según el Rol
        if (Login.rolUsuarioLogeado.equals("Docente")) {

            // Usamos el nombre de variable que encontraste
            btnborratabla.setEnabled(false);

            // Si quieres bloquear los otros de "Gestión" busca sus nombres
            // Ejemplo: btnGestionAlumnos.setVisible(false);
        }

        try {
            // Cargamos la imagen desde la ruta de paquetes
            setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/icono_pantalla1.png")));
        } catch (Exception e) {
            System.out.println("No se pudo cargar el icono");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnborratabla = new javax.swing.JButton();
        btngestioncalificaciones = new javax.swing.JButton();
        btingestioncurso = new javax.swing.JButton();
        btngestionalumno = new javax.swing.JButton();
        btnalumno = new javax.swing.JButton();
        btncurso = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnborratabla.setBackground(new java.awt.Color(0, 102, 204));
        btnborratabla.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnborratabla.setForeground(new java.awt.Color(255, 255, 255));
        btnborratabla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/contacto.png"))); // NOI18N
        btnborratabla.setText("Borrar datos de tabla");
        btnborratabla.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnborratabla.addActionListener(this::btnborratablaActionPerformed);
        getContentPane().add(btnborratabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 490, 60));

        btngestioncalificaciones.setBackground(new java.awt.Color(0, 102, 204));
        btngestioncalificaciones.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btngestioncalificaciones.setForeground(new java.awt.Color(255, 255, 255));
        btngestioncalificaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calificacion .png"))); // NOI18N
        btngestioncalificaciones.setText("Gestión de calificaciones");
        btngestioncalificaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btngestioncalificaciones.addActionListener(this::btngestioncalificacionesActionPerformed);
        getContentPane().add(btngestioncalificaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 490, 60));

        btingestioncurso.setBackground(new java.awt.Color(0, 102, 204));
        btingestioncurso.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btingestioncurso.setForeground(new java.awt.Color(255, 255, 255));
        btingestioncurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/copia-de-datos (1).png"))); // NOI18N
        btingestioncurso.setText("Gestión de cursos");
        btingestioncurso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btingestioncurso.addActionListener(this::btingestioncursoActionPerformed);
        getContentPane().add(btingestioncurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 240, 50));

        btngestionalumno.setBackground(new java.awt.Color(0, 102, 204));
        btngestionalumno.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btngestionalumno.setForeground(new java.awt.Color(255, 255, 255));
        btngestionalumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gestion.png"))); // NOI18N
        btngestionalumno.setText("Gestión de alumnos");
        btngestionalumno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btngestionalumno.addActionListener(this::btngestionalumnoActionPerformed);
        getContentPane().add(btngestionalumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 240, 60));

        btnalumno.setBackground(new java.awt.Color(0, 102, 204));
        btnalumno.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnalumno.setForeground(new java.awt.Color(255, 255, 255));
        btnalumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/graduado.png"))); // NOI18N
        btnalumno.setText("Alumnos");
        btnalumno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnalumno.addActionListener(this::btnalumnoActionPerformed);
        getContentPane().add(btnalumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 240, 60));

        btncurso.setBackground(new java.awt.Color(0, 102, 204));
        btncurso.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btncurso.setForeground(new java.awt.Color(255, 255, 255));
        btncurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aula.png"))); // NOI18N
        btncurso.setText("Cursos");
        btncurso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncurso.addActionListener(this::btncursoActionPerformed);
        getContentPane().add(btncurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 240, 50));

        btnsalir.setBackground(new java.awt.Color(102, 102, 102));
        btnsalir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnsalir.setForeground(new java.awt.Color(255, 255, 255));
        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar-sesion.png"))); // NOI18N
        btnsalir.setText("Salir");
        btnsalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsalir.addActionListener(this::btnsalirActionPerformed);
        getContentPane().add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 370, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnborratablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnborratablaActionPerformed

        Eliminar_tareas eliminar_tareas = new Eliminar_tareas();
        eliminar_tareas.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnborratablaActionPerformed

    private void btngestioncalificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngestioncalificacionesActionPerformed

        Gestion_calificaciones gestion_calificaciones = new Gestion_calificaciones();
        gestion_calificaciones.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btngestioncalificacionesActionPerformed

    private void btingestioncursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btingestioncursoActionPerformed

        Gestion_cursos gestion_cursos = new Gestion_cursos();
        gestion_cursos.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btingestioncursoActionPerformed

    private void btngestionalumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngestionalumnoActionPerformed

        Gestion_alumnos gestion_alumnos = new Gestion_alumnos();
        gestion_alumnos.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btngestionalumnoActionPerformed

    private void btnalumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnalumnoActionPerformed

        Registrar_alumnos registrar_alumnos = new Registrar_alumnos();
        registrar_alumnos.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnalumnoActionPerformed

    private void btncursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncursoActionPerformed

        Registro_curso registrar_curso = new Registro_curso();
        registrar_curso.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btncursoActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed

        this.dispose();

        // Abrir ventana Login
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_btnsalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Principal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btingestioncurso;
    private javax.swing.JButton btnalumno;
    private javax.swing.JButton btnborratabla;
    private javax.swing.JButton btncurso;
    private javax.swing.JButton btngestionalumno;
    private javax.swing.JButton btngestioncalificaciones;
    private javax.swing.JButton btnsalir;
    // End of variables declaration//GEN-END:variables
}
