package frames;

import javax.swing.JOptionPane;

import clases.Conectar;
import java.awt.Toolkit;
import java.io.UnsupportedEncodingException;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;

/**
 *
 * @author caill
 */
public class Registro_usuario extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Registro_usuario.class.getName());

    public Registro_usuario() {
        initComponents();
        configurarVentana();

        java.net.URL url = getClass().getResource("/imagenes/ojo_cerrado.png");
        if (url != null) {
            lblOjo1.setIcon(new javax.swing.ImageIcon(url));
            lblOjo2.setIcon(new javax.swing.ImageIcon(url));
        }

        try {
            // Cargamos la imagen desde la ruta de paquetes
            setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/icono_pantalla1.png")));
        } catch (Exception e) {
            System.out.println("No se pudo cargar el icono");
        }

    }

    private void configurarVentana() {
        this.setTitle("Registro de Usuario");
        this.setSize(707, 417);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txttelefono = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        txttiponivel = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtcontrasena = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        txtrepetircontrasena = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        cmbtiponivel = new javax.swing.JComboBox<>();
        btnregistro = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        lblOjo2 = new javax.swing.JLabel();
        lblOjo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Crear cuenta");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 150, 260));

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/anadir-grupo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 190));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Regristo de Nuevo Usuario");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        jLabel4.setText("Teléfono");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, -1, -1));
        getContentPane().add(txttelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 210, -1));

        jLabel5.setText("Email");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, -1, -1));
        getContentPane().add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 210, -1));

        jLabel6.setText("Nombre Completo");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, -1));
        getContentPane().add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 210, -1));
        getContentPane().add(txttiponivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 210, -1));

        jLabel7.setText("Tipo de Nivel");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, -1, -1));

        jLabel8.setText("Contraseña");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, -1, -1));
        getContentPane().add(txtusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 210, -1));

        jLabel9.setText("Nombre de Usuario");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, -1, -1));
        getContentPane().add(txtcontrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 210, -1));

        jLabel10.setText("Repetir Contraseña");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, -1, -1));
        getContentPane().add(txtrepetircontrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 210, -1));

        jLabel11.setText("Tipo de Nivel");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, -1, -1));

        cmbtiponivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione nivel:", "Administrador", "Docente" }));
        getContentPane().add(cmbtiponivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 210, -1));

        btnregistro.setBackground(new java.awt.Color(0, 153, 102));
        btnregistro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnregistro.setForeground(new java.awt.Color(255, 255, 255));
        btnregistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/comprobar 16px.png"))); // NOI18N
        btnregistro.setText("Registrar Usuario");
        btnregistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnregistro.addActionListener(this::btnregistroActionPerformed);
        getContentPane().add(btnregistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, -1, 40));

        btncancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btncancelar.setForeground(new java.awt.Color(102, 102, 102));
        btncancelar.setText("Cancelar");
        btncancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncancelar.addActionListener(this::btncancelarActionPerformed);
        getContentPane().add(btncancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, 100, 40));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/academico_black.png"))); // NOI18N
        jLabel12.setText("Sistema académico");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 350, -1, -1));

        lblOjo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ojo_cerrado.png"))); // NOI18N
        lblOjo2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblOjo2MousePressed(evt);
            }
        });
        getContentPane().add(lblOjo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 213, 30, 20));

        lblOjo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ojo_cerrado.png"))); // NOI18N
        lblOjo1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblOjo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblOjo1MousePressed(evt);
            }
        });
        getContentPane().add(lblOjo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 154, 30, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnregistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistroActionPerformed

        // 1. Obtener los datos
        String nombre = txtnombre.getText().trim();
        String email = txtemail.getText().trim();
        String telefono = txttelefono.getText().trim();
        String usuario = txtusuario.getText().trim();
        String pass = new String(txtcontrasena.getPassword());
        String repass = new String(txtrepetircontrasena.getPassword());
        String nivel = cmbtiponivel.getSelectedItem().toString();

        // 2. Validaciones de campos vacíos y coincidencia de clave
        if (nombre.isEmpty() || usuario.isEmpty() || pass.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, rellena los campos obligatorios.");
            return;
        }
        if (!pass.equals(repass)) {
            JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden.");
            return;
        }
        if (nivel.equals("Seleccione nivel:")) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar un nivel de usuario.");
            return;
        }

        // --- BLOQUEO DE SEGURIDAD PARA ADMINISTRADORES ---
        if (nivel.equals("Administrador")) {
            String adminKey = JOptionPane.showInputDialog(this, "Introduzca la Clave de Autorización para crear un Administrador:");

            // Si el usuario cancela o la clave es incorrecta, lo frenamos en seco
            if (adminKey == null || !adminKey.equals("Alemania.2026")) {
                JOptionPane.showMessageDialog(this, "Autorización denegada. Solo puedes registrarte como Docente.");
                return;
            }
        }
        // ------------------------------------------------

        // 3. CIFRADO
        String passCifrada = cifrarPassword(pass);

        try (Connection cn = Conectar.conexion()) {

            // --- VALIDAR SI EL USUARIO YA EXISTE ---
            PreparedStatement pstCheck = cn.prepareStatement("SELECT username FROM usuarios WHERE username = ?");
            pstCheck.setString(1, usuario);
            ResultSet rs = pstCheck.executeQuery();

            if (rs.next()) {
                JOptionPane.showMessageDialog(this, "El nombre de usuario ya existe. Elige otro.");
                return;
            }

            // 4. GUARDAR EN LA BASE DE DATOS
            String sql = "INSERT INTO usuarios (nombre, email, telefono, username, password, tipo_nivel) VALUES (?,?,?,?,?,?)";
            PreparedStatement pst = cn.prepareStatement(sql);

            pst.setString(1, nombre);
            pst.setString(2, email);
            pst.setString(3, telefono);
            pst.setString(4, usuario);
            pst.setString(5, passCifrada);
            pst.setString(6, nivel);

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "¡Usuario registrado con éxito!");
            Login login = new Login();
            login.setVisible(true);
            this.dispose();
            limpiarCampos();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al registrar: " + e.getMessage());
        }

    }//GEN-LAST:event_btnregistroActionPerformed

    private void lblOjo1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOjo1MousePressed

        try {
            // Usamos el primer campo para saber si está oculto o no
            if (txtcontrasena.getEchoChar() != (char) 0) {

                // 1. MOSTRAR en ambos campos
                txtcontrasena.setEchoChar((char) 0);
                txtrepetircontrasena.setEchoChar((char) 0);

                // 2. Cambiar iconos a "Abierto" (Recuerda usar los nombres sin espacios)
                java.net.URL imgAbierto = getClass().getResource("/imagenes/ojo_abierto.png");
                if (imgAbierto != null) {
                    javax.swing.ImageIcon iconoAbierto = new javax.swing.ImageIcon(imgAbierto);
                    lblOjo1.setIcon(iconoAbierto); // El ojo de arriba
                    lblOjo2.setIcon(iconoAbierto); // El ojo de abajo
                }

            } else {
                // 3. OCULTAR en ambos campos
                txtcontrasena.setEchoChar('•');
                txtrepetircontrasena.setEchoChar('•');

                // 4. Cambiar iconos a "Cerrado"
                java.net.URL imgCerrado = getClass().getResource("/imagenes/ojo_cerrado.png");
                if (imgCerrado != null) {
                    javax.swing.ImageIcon iconoCerrado = new javax.swing.ImageIcon(imgCerrado);
                    lblOjo1.setIcon(iconoCerrado);
                    lblOjo2.setIcon(iconoCerrado);
                }
            }
        } catch (Exception e) {
            System.err.println("Error en ojos de registro: " + e.getMessage());
        }

    }//GEN-LAST:event_lblOjo1MousePressed

    private void lblOjo2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOjo2MousePressed

        try {
            // Usamos el primer campo para saber si está oculto o no
            if (txtcontrasena.getEchoChar() != (char) 0) {

                // 1. MOSTRAR en ambos campos
                txtcontrasena.setEchoChar((char) 0);
                txtrepetircontrasena.setEchoChar((char) 0);

                // 2. Cambiar iconos a "Abierto" (Recuerda usar los nombres sin espacios)
                java.net.URL imgAbierto = getClass().getResource("/imagenes/ojo_abierto.png");
                if (imgAbierto != null) {
                    javax.swing.ImageIcon iconoAbierto = new javax.swing.ImageIcon(imgAbierto);
                    lblOjo1.setIcon(iconoAbierto); // El ojo de arriba
                    lblOjo2.setIcon(iconoAbierto); // El ojo de abajo
                }

            } else {
                // 3. OCULTAR en ambos campos
                txtcontrasena.setEchoChar('•');
                txtrepetircontrasena.setEchoChar('•');

                // 4. Cambiar iconos a "Cerrado"
                java.net.URL imgCerrado = getClass().getResource("/imagenes/ojo_cerrado.png");
                if (imgCerrado != null) {
                    javax.swing.ImageIcon iconoCerrado = new javax.swing.ImageIcon(imgCerrado);
                    lblOjo1.setIcon(iconoCerrado);
                    lblOjo2.setIcon(iconoCerrado);
                }
            }
        } catch (Exception e) {
            System.err.println("Error en ojos de registro: " + e.getMessage());
        }

    }//GEN-LAST:event_lblOjo2MousePressed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        this.dispose();

        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_btncancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Registro_usuario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnregistro;
    private javax.swing.JComboBox<String> cmbtiponivel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblOjo1;
    private javax.swing.JLabel lblOjo2;
    private javax.swing.JPasswordField txtcontrasena;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JPasswordField txtrepetircontrasena;
    private javax.swing.JTextField txttelefono;
    private javax.swing.JTextField txttiponivel;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables

    private void limpiarCampos() {
        txtnombre.setText("");
        txtemail.setText("");
        txttelefono.setText("");
        txtusuario.setText("");
        txtcontrasena.setText("");
        txtrepetircontrasena.setText("");
        txttiponivel.setText("");
        cmbtiponivel.setSelectedIndex(0);
    }

    public String cifrarPassword(String password) {
        try {
            java.security.MessageDigest md = java.security.MessageDigest.getInstance("SHA-256");
            byte[] hash = md.digest(password.getBytes("UTF-8"));
            StringBuilder sb = new StringBuilder();
            for (byte b : hash) {
                sb.append(String.format("%02x", b));
            }
            return sb.toString();
        } catch (UnsupportedEncodingException | NoSuchAlgorithmException e) {
            throw new RuntimeException(e);
        }
    }

}
