package frames;

import clases.Conectar;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author caill
 */
public class Registrar_alumnos extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Registrar_alumnos.class.getName());

    public Registrar_alumnos() {
        initComponents();
        this.setResizable(false);
        this.setTitle("Registrar Alumnos");
        this.setSize(640, 480);
        this.setLocationRelativeTo(null);

        //txtidalumno.setVisible(true);
        txtidalumno.setEditable(false);
        this.cargarTabla("");
        this.cargarComboMateria();
        this.txtcantidad.setEditable(false);

        try {
            // Cargamos la imagen desde la ruta de paquetes
            setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/icono_pantalla1.png")));
        } catch (Exception e) {
            System.out.println("No se pudo cargar el icono");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtidalumno = new javax.swing.JTextField();
        txtapellidos = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txttelefono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cmbmateria = new javax.swing.JComboBox<>();
        cmbgrado = new javax.swing.JComboBox<>();
        btnregistrar = new javax.swing.JButton();
        btnactualizar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnvolver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaregistroalumno = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtcantidad = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtbuscar = new javax.swing.JTextField();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Alumnos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Id alumno: ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        jLabel3.setText("Apellidos:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, -1, -1));

        txtidalumno.setEnabled(false);
        jPanel1.add(txtidalumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 140, -1));

        txtapellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtapellidosKeyTyped(evt);
            }
        });
        jPanel1.add(txtapellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 140, -1));

        txtnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombreKeyTyped(evt);
            }
        });
        jPanel1.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 140, -1));

        jLabel4.setText("Grado:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        jLabel5.setText("Teléfono:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, -1));

        txttelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttelefonoKeyTyped(evt);
            }
        });
        jPanel1.add(txttelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 140, -1));

        jLabel6.setText("Materia:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, -1, -1));

        cmbmateria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione materia:" }));
        cmbmateria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(cmbmateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 150, -1));

        cmbgrado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione grado:", "1A", "1B", "2A", "2B", "3A", "3B", "4A", "4B", "5A", "5B", "6A", "6B", "7A", "7B", "8A", "8B" }));
        cmbgrado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmbgrado.addActionListener(this::cmbgradoActionPerformed);
        jPanel1.add(cmbgrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 140, -1));

        btnregistrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnregistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disquete.png"))); // NOI18N
        btnregistrar.setText("Registrar");
        btnregistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnregistrar.addActionListener(this::btnregistrarActionPerformed);
        jPanel1.add(btnregistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        btnactualizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnactualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar.png"))); // NOI18N
        btnactualizar.setText("Actualizar");
        btnactualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnactualizar.addActionListener(this::btnactualizarActionPerformed);
        jPanel1.add(btnactualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, -1));

        btneliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/borrar.png"))); // NOI18N
        btneliminar.setText("Eliminar");
        btneliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btneliminar.addActionListener(this::btneliminarActionPerformed);
        jPanel1.add(btneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 150, -1, -1));

        btnvolver.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnvolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/volver.png"))); // NOI18N
        btnvolver.setText("Volver");
        btnvolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnvolver.addActionListener(this::btnvolverActionPerformed);
        jPanel1.add(btnvolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 580, 220));

        tablaregistroalumno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaregistroalumno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tablaregistroalumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaregistroalumnoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaregistroalumno);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 580, 140));

        jLabel7.setText("Buscar:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        txtcantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcantidadKeyTyped(evt);
            }
        });
        getContentPane().add(txtcantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 150, -1));

        jLabel8.setText("Cantidad:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, -1, -1));

        txtbuscar.addActionListener(this::txtbuscarActionPerformed);
        txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbuscarKeyTyped(evt);
            }
        });
        getContentPane().add(txtbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 150, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isLetter(c) && c != ' ') {
            evt.consume();
        }


    }//GEN-LAST:event_txtnombreKeyTyped

    private void txtapellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapellidosKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isLetter(c) && c != ' ') {
            evt.consume();
        }

    }//GEN-LAST:event_txtapellidosKeyTyped

    private void txttelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelefonoKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            evt.consume();
        }

    }//GEN-LAST:event_txttelefonoKeyTyped

    private void txtbuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isLetter(c) && c != ' ') {
            evt.consume();
        }
    }//GEN-LAST:event_txtbuscarKeyTyped

    private void txtcantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcantidadKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtcantidadKeyTyped

    private void tablaregistroalumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaregistroalumnoMouseClicked
        int fila = tablaregistroalumno.getSelectedRow();

        if (fila >= 0) {

            if (fila >= 0) {

                txtidalumno.setText(tablaregistroalumno.getValueAt(fila, 0).toString());
                txtnombre.setText(tablaregistroalumno.getValueAt(fila, 1).toString());
                txtapellidos.setText(tablaregistroalumno.getValueAt(fila, 2).toString());
                cmbgrado.setSelectedItem(tablaregistroalumno.getValueAt(fila, 3).toString());
                txttelefono.setText(tablaregistroalumno.getValueAt(fila, 4).toString());
                cmbmateria.setSelectedItem(tablaregistroalumno.getValueAt(fila, 5).toString());
            }
        }
    }//GEN-LAST:event_tablaregistroalumnoMouseClicked

    private void btnregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarActionPerformed

        String nombre = txtnombre.getText().trim();
        String apellidos = txtapellidos.getText().trim();
        String grado = cmbgrado.getSelectedItem().toString();
        String telefono = txttelefono.getText().trim();
        String materia = cmbmateria.getSelectedItem().toString();

        if (nombre.isEmpty() || apellidos.isEmpty() || telefono.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Complete todos los campos");
            return;
        }

        if (cmbmateria.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Seleccione una materia");
            return;
        }

        try {
            Connection con = Conectar.conexion();

            // 1. Buscamos el ID del curso seleccionado
            String sqlCurso = "SELECT id_curso FROM curso WHERE nombre_curso = ?";
            PreparedStatement psCurso = con.prepareStatement(sqlCurso);
            psCurso.setString(1, materia);
            ResultSet rs = psCurso.executeQuery();

            int idCurso = 0;
            if (rs.next()) {
                idCurso = rs.getInt("id_curso");
            }

            rs.close();
            psCurso.close();

            // 2. MODIFICACIÓN: Agregamos id_docente al final del INSERT
            String sql = "INSERT INTO alumnos (nombre, apellidos, grado, telefono, id_curso_asignado, id_docente) VALUES (?,?,?,?,?,?)";
            PreparedStatement ps = con.prepareStatement(sql);

            ps.setString(1, nombre);
            ps.setString(2, apellidos);
            ps.setString(3, grado);
            ps.setString(4, telefono);
            ps.setInt(5, idCurso);

            // 3. AQUÍ LA MAGIA: Mandamos el ID del docente logueado
            ps.setInt(6, Login.idUsuarioLogeado);

            ps.executeUpdate();

            JOptionPane.showMessageDialog(this, "Alumno registrado correctamente");

            ps.close();
            con.close();

            limpiarCampos();
            cargarTabla(""); // Ahora sí aparecerá porque ya tiene dueño

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al guardar: " + e.getMessage());
        }
    }//GEN-LAST:event_btnregistrarActionPerformed

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed

        String id = txtidalumno.getText();
        String nombre = txtnombre.getText().trim();
        String apellidos = txtapellidos.getText().trim();
        String grado = cmbgrado.getSelectedItem().toString();
        String telefono = txttelefono.getText().trim();
        String materia = cmbmateria.getSelectedItem().toString();

        if (id.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Seleccione un alumno de la tabla");
            return;
        }
        if (nombre.isEmpty() || apellidos.isEmpty() || telefono.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Complete todos los campos");
            return;
        }

        if (cmbmateria.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Seleccione una materia");
            return;
        }

        try {

            Connection con = Conectar.conexion();

            String sqlCurso = "SELECT id_curso FROM curso WHERE nombre_curso = ?";
            PreparedStatement psCurso = con.prepareStatement(sqlCurso);
            psCurso.setString(1, materia);
            ResultSet rs = psCurso.executeQuery();

            int idCurso = 0;

            if (rs.next()) {
                idCurso = rs.getInt("id_curso");
            }

            rs.close();
            psCurso.close();

            String sql = "UPDATE alumnos SET nombre=?, apellidos=?, grado=?, telefono=?, id_curso_asignado=? WHERE id_alumno=?";
            PreparedStatement ps = con.prepareStatement(sql);

            ps.setString(1, nombre);
            ps.setString(2, apellidos);
            ps.setString(3, grado);
            ps.setString(4, telefono);
            ps.setInt(5, idCurso);
            ps.setInt(6, Integer.parseInt(id));

            ps.executeUpdate();

            JOptionPane.showMessageDialog(this, "Alumno actualizado correctamente");

            ps.close();
            con.close();

            limpiarCampos();
            cargarTabla("");

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al actualizar: " + e.getMessage());
        }


    }//GEN-LAST:event_btnactualizarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed

        String id = txtidalumno.getText();

        if (id.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Seleccione un alumno de la tabla");
            return;
        }

        int confirmacion = JOptionPane.showConfirmDialog(
                this,
                "¿Está seguro que desea eliminar este alumno?",
                "Confirmar eliminación",
                JOptionPane.YES_NO_OPTION
        );

        if (confirmacion == JOptionPane.YES_OPTION) {

            try {

                Connection con = Conectar.conexion();
                String sql = "DELETE FROM alumnos WHERE id_alumno = ?";
                PreparedStatement ps = con.prepareStatement(sql);

                ps.setInt(1, Integer.parseInt(id));

                ps.executeUpdate();

                JOptionPane.showMessageDialog(this, "Alumno eliminado correctamente");

                ps.close();
                con.close();

                limpiarCampos();
                cargarTabla("");
                tablaregistroalumno.clearSelection();

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Error al eliminar: " + e.getMessage());
            }
        }

    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvolverActionPerformed

        this.dispose();

        Principal principal = new Principal();
        principal.setVisible(true);

    }//GEN-LAST:event_btnvolverActionPerformed

    private void txtbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarActionPerformed

    private void txtbuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyReleased
        cargarTabla(txtbuscar.getText());
    }//GEN-LAST:event_txtbuscarKeyReleased

    private void cmbgradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbgradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbgradoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Registrar_alumnos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnregistrar;
    private javax.swing.JButton btnvolver;
    private javax.swing.JComboBox<String> cmbgrado;
    private javax.swing.JComboBox<String> cmbmateria;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaregistroalumno;
    private javax.swing.JTextField txtapellidos;
    private javax.swing.JTextField txtbuscar;
    private javax.swing.JTextField txtcantidad;
    private javax.swing.JTextField txtidalumno;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables

    private void cargarTabla(String valor) {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellidos");
        modelo.addColumn("Grado");
        modelo.addColumn("Telefono");
        modelo.addColumn("Materia");

        tablaregistroalumno.setModel(modelo);

        // 1. Modificamos el SQL para incluir id_docente
        // Usamos AND (CondicionBusqueda) para que se cumplan ambos filtros
        String sql = "SELECT a.id_alumno, a.nombre, a.apellidos, a.grado, a.telefono, c.nombre_curso "
                + "FROM alumnos a "
                + "INNER JOIN curso c ON a.id_curso_asignado = c.id_curso "
                + "WHERE a.id_docente = ? AND (a.nombre LIKE ? OR a.apellidos LIKE ?)";

        try {
            Connection con = Conectar.conexion();
            PreparedStatement ps = con.prepareStatement(sql);

            // 2. Pasamos el ID del docente logueado (el que guardamos en el Login)
            ps.setInt(1, Login.idUsuarioLogeado);

            // 3. Los parámetros de búsqueda pasan a ser el 2 y el 3
            ps.setString(2, "%" + valor + "%");
            ps.setString(3, "%" + valor + "%");

            ResultSet rs = ps.executeQuery();
            int contador = 0;

            while (rs.next()) {
                Object[] fila = new Object[6];
                fila[0] = rs.getInt(1);
                fila[1] = rs.getString(2);
                fila[2] = rs.getString(3);
                fila[3] = rs.getString(4);
                fila[4] = rs.getString(5);
                fila[5] = rs.getString(6);

                modelo.addRow(fila);
                contador++;
            }

            txtcantidad.setText(String.valueOf(contador));

            rs.close();
            ps.close();
            con.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al buscar: " + e.getMessage());
        }
    }

    private void cargarComboMateria() {

        String sql = "SELECT id_curso, nombre_curso FROM curso";

        try {
            Connection con = Conectar.conexion();
            PreparedStatement ps = con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            cmbmateria.removeAllItems();
            cmbmateria.addItem("Seleccione materia:");

            while (rs.next()) {
                cmbmateria.addItem(rs.getString("nombre_curso"));
            }

            rs.close();
            ps.close();
            con.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar materias: " + e.getMessage());
        }
    }

    private void limpiarCampos() {
        txtidalumno.setText("");
        txtnombre.setText("");
        txtapellidos.setText("");
        txttelefono.setText("");
        cmbgrado.setSelectedIndex(0);
        cmbmateria.setSelectedIndex(0);
    }

}
