package frames;

import javax.swing.JOptionPane;
import clases.Conectar;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;

/**
 *
 * @author caill
 */
public class Registro_curso extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Registro_curso.class.getName());

    public Registro_curso() {
        initComponents();
        this.setResizable(false);
        this.setTitle("Registrar Cursos");
        this.setSize(640, 480);
        this.setLocationRelativeTo(null);

        txtidcurso.setEditable(false);
        this.cargarTabla();

        try {
            // Cargamos la imagen desde la ruta de paquetes
            setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/icono_pantalla1.png")));
        } catch (Exception e) {
            System.out.println("No se pudo cargar el icono");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        txtidcurso = new javax.swing.JTextField();
        btnguardar = new javax.swing.JButton();
        btnactualizar = new javax.swing.JButton();
        btnvolver = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_registro_cursos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cursos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Id:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));
        jPanel1.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 160, -1));

        txtidcurso.setEnabled(false);
        jPanel1.add(txtidcurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 160, -1));

        btnguardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disquete.png"))); // NOI18N
        btnguardar.setText("Registrar");
        btnguardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnguardar.addActionListener(this::btnguardarActionPerformed);
        jPanel1.add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, -1, -1));

        btnactualizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnactualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar.png"))); // NOI18N
        btnactualizar.setText("Actualizar");
        btnactualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnactualizar.addActionListener(this::btnactualizarActionPerformed);
        jPanel1.add(btnactualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, -1, -1));

        btnvolver.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnvolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/volver.png"))); // NOI18N
        btnvolver.setText("Volver");
        btnvolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnvolver.addActionListener(this::btnvolverActionPerformed);
        jPanel1.add(btnvolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 99, 120, -1));

        btneliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/borrar.png"))); // NOI18N
        btneliminar.setText("Eliminar");
        btneliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btneliminar.addActionListener(this::btneliminarActionPerformed);
        jPanel1.add(btneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 99, 116, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 570, 160));

        tabla_registro_cursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla_registro_cursos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabla_registro_cursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_registro_cursosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_registro_cursos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 570, 190));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed

        String nombre = txtnombre.getText().trim();

        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El nombre del curso es obligatorio");
            return;
        }

        try {
            Connection con = Conectar.conexion();

            String sql = "INSERT INTO curso (nombre_curso) VALUES (?)";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, nombre);

            ps.executeUpdate();

            JOptionPane.showMessageDialog(this, "Curso guardado correctamente");

            txtnombre.setText("");
            this.cargarTabla();

            con.close();

        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al guardar: " + e.getMessage());
        }


    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed

        String id = txtidcurso.getText();
        String nombre = txtnombre.getText().trim();

        if (id.isEmpty() || nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Seleccione un curso y modifique el nombre");
            return;
        }

        try {
            Connection con = Conectar.conexion();

            String sql = "UPDATE curso SET nombre_curso=? WHERE id_curso=?";
            PreparedStatement ps = con.prepareStatement(sql);

            ps.setString(1, nombre);
            ps.setInt(2, Integer.parseInt(id));

            ps.executeUpdate();

            JOptionPane.showMessageDialog(this, "Curso actualizado correctamente");

            txtnombre.setText("");
            txtidcurso.setText("");

            cargarTabla();

            con.close();

        } catch (HeadlessException | NumberFormatException | SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al actualizar: " + e.getMessage());
        }

    }//GEN-LAST:event_btnactualizarActionPerformed

    private void tabla_registro_cursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_registro_cursosMouseClicked
        int fila = tabla_registro_cursos.getSelectedRow();

        if (fila >= 0) {
            txtidcurso.setText(tabla_registro_cursos.getValueAt(fila, 0).toString());
            txtnombre.setText(tabla_registro_cursos.getValueAt(fila, 1).toString());
        }

    }//GEN-LAST:event_tabla_registro_cursosMouseClicked

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed

        String id = txtidcurso.getText();

        if (id.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Seleccione un curso para eliminar");
            return;
        }

        int confirmacion = JOptionPane.showConfirmDialog(
                this,
                "¿Está seguro que desea eliminar este curso?",
                "Confirmar eliminación",
                JOptionPane.YES_NO_OPTION
        );

        if (confirmacion == JOptionPane.YES_OPTION) {

            try {
                Connection con = Conectar.conexion();

                String sql = "DELETE FROM curso WHERE id_curso=?";
                PreparedStatement ps = con.prepareStatement(sql);
                ps.setInt(1, Integer.parseInt(id));

                ps.executeUpdate();

                JOptionPane.showMessageDialog(this, "Curso eliminado correctamente");

                txtidcurso.setText("");
                txtnombre.setText("");

                cargarTabla(); // refresca la tabla

                con.close();

            } catch (HeadlessException | NumberFormatException | SQLException e) {
                JOptionPane.showMessageDialog(this, "Error al eliminar: " + e.getMessage());
            }
        }

    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvolverActionPerformed
        this.dispose();

        Principal principal = new Principal();
        principal.setVisible(true);
    }//GEN-LAST:event_btnvolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Registro_curso().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnvolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla_registro_cursos;
    private javax.swing.JTextField txtidcurso;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables

    private void cargarTabla() {

        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Nombre del Curso");

        tabla_registro_cursos.setModel(modelo);

        String sql = "SELECT * FROM curso";

        try {
            Connection con = Conectar.conexion();
            PreparedStatement ps = con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                Object[] fila = new Object[2];
                fila[0] = rs.getInt("id_curso");
                fila[1] = rs.getString("nombre_curso");
                modelo.addRow(fila);
            }

            con.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar tabla: " + e.getMessage());
        }
    }

}
